### ISSUE TITLE
Mount changes when not using perch bootparam

### ISSUE THREAD

**Issue by James-Mat** [Tomas-M/linux-live#162] opened 2021-08-25 10:23 UTC
Hello!

I'm a bit confused whether I might be doing something wrongly:
I added two entries to the boot menu, one being the default, the other the default with 'perch' appended.
What I had hoped was that I can boot into the latter, make changes, and then boot into the first without 'perch' with these changes still applied (and any further changes being discarded on reboot).

However, changes made with perch are persistent, but only when booting with perch. So any changes I make with perch are still there after I reboot with perch, but aren't loaded when I boot without perch afterwards.
Is this the expected behaviour?
If so, is it possible to mount the changes into aufs while also booting ro some other way?

**Comment by Tomas-M** [comment] 2021-08-25 10:33
Yes this is intended behavior.
You can create a squashfs module with your changes and copy it to /linux/modules directory to load it on boot.
You will find changed files while running your distro with 'perch' parameter mounted in /run/initramfs/... somewhere (I don't remember exactly)

**Comment by Tomas-M** [comment] 2022-03-09 10:41
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.

**Closed by Tomas-M** 2022-03-09 10:41 UTC
