### ISSUE TITLE
Cannot find an executable init file

### ISSUE THREAD

**Issue by tree-t** [Tomas-M/linux-live#200] opened 2022-03-09 10:29 UTC
Hello Tomas,
As I was going to test a modified version of (slax 9.11.0) named slux(just because I wanted to test out the version modified by me, but didn't want to call it SLAX).
I noticed, that the live-kit says that there is no init found and I checked to see if there is any, but confirmed that there was no `/memory/union/usr/*bin/init`.
Here is a pic of the situation:
![Screenshot_20220309-154743_VNC Viewer](https://user-images.githubusercontent.com/98072621/157423253-4fe556d0-291a-4c36-a3c1-5100bf3254d6.jpg)
But if I unsquashfs my .sb file(named debootstrap.sb), it shows:
![Screenshot_20220309-155001_Termux](https://user-images.githubusercontent.com/98072621/157423498-8663ab6e-eeb0-4b9c-8087-5cd01cce9d8d.jpg)
Is there a problem in naming or is it a live kit fault?

**Comment by Tomas-M** [comment] 2022-03-09 10:37
Hm, since it is blue, isn't it a symlink? Perhaps broken symlink? Try ls -l
(lowercase L)

Try 'mount' to see what modules are mounted, maybe your sb file is not mounted?

**Comment by Tomas-M** [comment] 2022-03-09 10:46
I am closing this issue because I think it is not a problem of linux-live.
Please reopen if you have additional questions or if you could provide additional feedback. Thanks

**Closed by Tomas-M** 2022-03-09 10:46 UTC

**Comment by tree-t** [comment] 2022-03-09 12:35
Result of `ls -l init`:
![Screenshot_20220309-175549_Termux](https://user-images.githubusercontent.com/98072621/157442007-39efbb77-d97b-4672-9151-0cc7b35c56e1.jpg)
Result of `ls /memory/bundles/`:
![Screenshot_20220309-175740_VNC Viewer](https://user-images.githubusercontent.com/98072621/157442098-f0c5c410-8bc9-4f87-b308-c880ea344367.jpg)
Please Note, since I thought that the problem was due to debootstrap.sb not having a numerical starting. Hence, I renamed it to 001-debootstrap.sb

**Comment by tree-t** [comment] 2022-03-09 13:07
Ok, will try

**Comment by tree-t** [comment] 2022-03-09 13:28
Ok,
Here is the link to my debootstrap.sb file(83 mb).
[Debootstrap.sb](https://1drv.ms/u/s!Ak2-zM32CYoabdGwdDnazu9ExrQ?e=v6btbm) 
Click on it to view it.

**Comment by Tomas-M** [comment] 2022-03-09 13:42
I can see where is the problem now.
There is a check in linux-live startup script, which tries to guess where is the init
This check uses if [ -x ... ]
The problem is, that since your init is a symlink to absolute path /lib/systemd/systemd, the check always fails. Because at the moment of the -x check, the link seems broken, since there is no /lib/systemd/systemd
In order to fix the problem, you can try this: edit the symlink and use relative path
like this:

    #!/bin/bash
    sb2dir 001-debootstrap.sb
    cd 001-debootstrap.sb/usr/bin
    rm init
    ln -s ../lib/systemd/systemd init
    dir2sb 001-debootstrap.sh

I should perhaps rewrite the check in linux-live in order to not fail in this case.

**Comment by Tomas-M** [comment] 2022-03-09 13:43
Let me know please if the suggestion helped. Thanks

**Comment by Tomas-M** [comment] 2022-03-09 13:51
I think I confused myself.
The check is -x or -L ... this means if there is a symlink, it should continue without any trouble.
And that is what happens actually, if I put the module to ISO, it boots just fine.
So I really do not see any problem anymore. Strange.

**Comment by Tomas-M** [comment] 2022-03-09 16:37
Hm, now I noticed you are using Slax 9.x as a base.
I am using Slax 11.2 as a base.
But the necessary changes were made 5 years ago so it should be in Slax 9  too. https://github.com/Tomas-M/linux-live/commit/35d6b2364f03e023d72df852c38b94116eafb40d
Is it a possibility for you to switch to Slax 11 ?
