### ISSUE TITLE
Looking for linux data in /linux .........................

### ISSUE THREAD

**Issue by Mordillo98** [Tomas-M/linux-live#98] opened 2020-02-04 16:48 UTC
Hi,

   I'm getting this error while loading either the ISO, or USB.

![Screen Shot 2020-02-04 at 11 29 52 AM](https://user-images.githubusercontent.com/26201289/73766592-3a51a980-4744-11ea-8089-e093e08545de.png)

This is the ISO content....

![Screen Shot 2020-02-04 at 11 45 43 AM](https://user-images.githubusercontent.com/26201289/73766616-43db1180-4744-11ea-97ba-620ba19f81d3.png)

Not sure what to do from here...

Thx !

**Comment by csyperski** [comment] 2020-06-12 13:24
Same issue here, rebuilt multiple times, not able to get working.  Tried with master and 2.3 without any success on ubuntu 18.04 x64

**Comment by chyldofthebeat** [comment] 2020-10-02 20:20
I have this issue as well, though I have info to add!!!

I found success copying the linux/ directory to a USB thumb drive and that works!! yet the same exact build, copying to both a very old Sata II SSD connected to a USB adapter, and a new M.2 SSD connected to a USB enclosure, both exhibit this same behavior of not finding the data file in the linux directory. 

The only difference setup-wise that I can see between the thumb drive and the SSDs is that the thumb drive does not contain a partition table, and the SSDs were set up with msdos type partition table. 

This is on a system that is booting via BIOS method, not UEFI. 

When I looked at the debug log it didn't seem to show anything useful. 

If there are any other logs that get created or any other super-verbose way it could be run other than just debug mode, let me know!

Tried from Linux Mint 20, with both master and 2.3 

Note I didn't run the script that creates the zip file, since my build machine is lacking in enough space. 

However it did build with plenty of space to spare, so I don't think that impacted the regular build.

**Comment by rostok** [comment] 2020-10-17 22:50
I am not quite sure but this may be relevant to modules being placed on NVME SSD drive. I had no troubles running Slax from IDE drive but had similar hangup on "looking for /slax data" text when I changed VM storage controller to NVME. I think that the `blkid` command doesn't yield any devices during init https://github.com/Tomas-M/linux-live/blob/master/livekitlib#L522. However getting into sh and executing manually `blkid /dev/nvme0n1p1` and running `sh /init` got me going. Note that after this blkid will return not only zram but also nvme partition. Maybe this helps.

**Comment by rostok** [comment] 2020-10-19 16:21
OK, I can confirm, that this issue is solved by adding 
```sh

#################################
echo Probing NVME ...............
blkid /dev/nvme0n1p1
blkid | grep -v zram
echo Probing NVME done
#################################

```
to /init in initrfs.img just after `modprobe_everything -v /drivers/net/`

I won't make any merge request as I am not particularly skilled with linux development and not quite sure this is the right place for this. Anyway hope it helps.

**Comment by Alaaask** [comment] 2020-11-22 14:45
> I have this issue as well, though I have info to add!!!
> 
> I found success copying the linux/ directory to a USB thumb drive and that works!! yet the same exact build, copying to both a very old Sata II SSD connected to a USB adapter, and a new M.2 SSD connected to a USB enclosure, both exhibit this same behavior of not finding the data file in the linux directory.
> 
> The only difference setup-wise that I can see between the thumb drive and the SSDs is that the thumb drive does not contain a partition table, and the SSDs were set up with msdos type partition table.
> 
> This is on a system that is booting via BIOS method, not UEFI.
> All target devices are formatted ext4.
> 
> When I looked at the debug log it didn't seem to show anything useful.
> 
> If there are any other logs that get created or any other super-verbose way it could be run other than just debug mode, let me know!
> 
> Tried from Linux Mint 20, with both master and 2.3
> 
> Note I didn't run the script that creates the zip file, since my build machine is lacking in enough space.
> 
> However it did build with plenty of space to spare, so I don't think that impacted the regular build.

I got the same error when tried installing Slax on my SSD, and at first I also failed loading. 
But it worked when I inserted the SSD and used the msata interface of the computer rather than connected the hard disk to a USB adpater.
Hope this helps.

**Comment by bryankaufmanatnetapp** [comment] 2020-12-09 22:58
I am also trying to install Slax but in Hyper-V on a virtual ide disk which appears as sda1. I found a Slax blog commentary about removing 'automount' from syslinux.cfg but that did not help.

**Comment by h7mojo** [comment] 2021-04-30 17:43
hi guys!

i'm using linux-live on usb within vmware ws. after usb flash got broken (became r/o) and then was healed i re-created a vm but got this error. after i replaced scsi controller for boot disk with ide the issue had gone.
maybe helps smb.

**Comment by computermaster0101** [comment] 2022-02-26 20:27
Hey Tomas! Its been a while! I'm having the same issue. Interestingly if I take the SSD out of the USB enclosure and install it directly into a NUC as the primary drive it is seen as /dev/sda and starts up with no issue. I will continue working on the issue and will update if I identify a resolution.

I'll test the solution from ROSTOK and update if resolved.

**Comment by computermaster0101** [comment] 2022-03-02 01:47
Figured it out. UAS driver is USB Attached SCSII. This is the driver Linux and Windows refers to when the USB device is attached. I referred to https://github.com/Tomas-M/linux-live/issues/83 to identify the driver. 

used 
usb-devices
to identify the driver is uas

used modinfo uas to identify driver location. 

once the driver location was identified i was able to update initramfs_create to include 
copy_including_deps /$LMK/kernel/drivers/usb/storage/uas.*

**Comment by mapagm** [comment] 2022-03-03 11:15
Hi all,

I have this error when tried installing Slax on my SSD or VMware. Is there any solution to this problem? **@computermaster0101** can You do some "how to" for noobs? :)

**Comment by computermaster0101** [comment] 2022-03-03 13:28
initramfs_create is located at linux-live/initramfs/initramfs_create

Try this as a sledgehammer approach. (i think this was line 99 in initramfs_create)

copy_including_deps /$LMK/kernel/drivers/usb/storage/usb-storage.*
to 
copy_including_deps /$LMK/kernel/drivers/usb/storage


If it works, the surgical approach is to identify the driver used by the device (usb-devices is the command) then identify the driver location (modinfo is the command). 

From modinfo, you will see the filename as something along the lines of 
/lib/modules/5.13.0-30-generic/kernel/drivers/usb/storage/uas.ko 

if you can identify the specific file for the driver you would need to add it to initramfs_create by inserting the following into the list of driversfor this example. 
copy_including_deps /$LMK/kernel/drivers/usb/storage/uas.*

**Comment by Tomas-M** [comment] 2022-03-09 10:44
I am closing all issues to make some cleanup.
Please reopen if you still need to, yet I cannot guarantee that I can help with your current issue.

**Closed by Tomas-M** 2022-03-09 10:44 UTC
